import {
  DispatchOfferStatus,
  GetProviderDispatchTabQuaryQuery,
  GetProviderMarketplaceTabQuaryQuery,
  MyWalletComplianceQuery,
  MyWalletQuery,
  MyWalletTransactionsQuery,
  ShipmentStatus,
  TransactionDirection,
  TransactionStatus,
  TransactionType,
  WalletAccountStatus,
} from "@/gql/graphql";

export const DEV_DISPATCH_DATA: GetProviderDispatchTabQuaryQuery = {
  myDispatchOffers: [
    {
      __typename: "DispatchOffer",
      id: "offer-001",
      batchId: "batch-001",
      providerId: "provider-001",
      shipmentId: "ship-001",
      vehicleId: null,
      status: DispatchOfferStatus.Accepted,
      sentAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      respondedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      expiresAt: null,
      providerEtaMinutes: 15,
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    },
    {
      __typename: "DispatchOffer",
      id: "offer-002",
      batchId: "batch-002",
      providerId: "provider-001",
      shipmentId: "ship-002",
      vehicleId: null,
      status: DispatchOfferStatus.Sent,
      sentAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      respondedAt: null,
      expiresAt: new Date(Date.now() + 1000 * 60 * 10).toISOString(),
      providerEtaMinutes: null,
      createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
    {
      __typename: "DispatchOffer",
      id: "offer-003",
      batchId: "batch-003",
      providerId: "provider-001",
      shipmentId: "ship-003",
      vehicleId: null,
      status: DispatchOfferStatus.Declined,
      sentAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      respondedAt: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
      expiresAt: null,
      providerEtaMinutes: null,
      createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    },
  ],
  getProviderDashboardQuary: {
    __typename: "ProviderDashboardQuary",
    activeAssignments: [
      {
        __typename: "Shipment",
        id: "ship-001",
        trackingCode: "OY-2024-0042",
        status: ShipmentStatus.EnRoutePickup,
        pickupAddressId: "addr-001",
        dropoffAddressId: "addr-002",
        scheduledAt: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        packageDescription: "Electronics – handle with care",
        pricingCurrency: "NGN",
        quotedPriceMinor: 350000,
        finalPriceMinor: null,
      },
      {
        __typename: "Shipment",
        id: "ship-004",
        trackingCode: "OY-2024-0043",
        status: ShipmentStatus.Assigned,
        pickupAddressId: "addr-003",
        dropoffAddressId: "addr-004",
        scheduledAt: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        packageDescription: "Clothing items",
        pricingCurrency: "NGN",
        quotedPriceMinor: 180000,
        finalPriceMinor: null,
      },
    ],
  },
};

export const DEV_WALLET_DATA: MyWalletQuery = {
  myWallet: {
    __typename: "WalletAccount",
    id: "wallet-001",
    ownerProfileId: "provider-001",
    currency: "NGN",
    balanceMinor: 425000,
    escrowMinor: 75000,
    status: WalletAccountStatus.Active,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
};

export const DEV_WALLET_COMPLIANCE_DATA: MyWalletComplianceQuery = {
  myWalletCompliance: {
    __typename: "WalletCompliance",
    phoneVerified: true,
    canFund: true,
    canWithdraw: true,
    blockReasons: [],
  },
};

export const DEV_WALLET_TRANSACTIONS_DATA: MyWalletTransactionsQuery = {
  myWalletTransactions: {
    __typename: "WalletTransactionsConnection",
    nextCursor: null,
    hasMore: false,
    items: [
      {
        __typename: "Transaction",
        id: "txn-001",
        walletAccountId: "wallet-001",
        direction: TransactionDirection.Credit,
        transactionType: TransactionType.ProviderPayout,
        amountMinor: 350000,
        currency: "NGN",
        status: TransactionStatus.Completed,
        reference: "PAY-REF-001",
        shipmentId: "ship-001",
        metadata: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        __typename: "Transaction",
        id: "txn-002",
        walletAccountId: "wallet-001",
        direction: TransactionDirection.Debit,
        transactionType: TransactionType.Withdrawal,
        amountMinor: 200000,
        currency: "NGN",
        status: TransactionStatus.Completed,
        reference: "WD-REF-002",
        shipmentId: null,
        metadata: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      },
      {
        __typename: "Transaction",
        id: "txn-003",
        walletAccountId: "wallet-001",
        direction: TransactionDirection.Credit,
        transactionType: TransactionType.Topup,
        amountMinor: 500000,
        currency: "NGN",
        status: TransactionStatus.Completed,
        reference: "TOP-REF-003",
        shipmentId: null,
        metadata: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      },
      {
        __typename: "Transaction",
        id: "txn-004",
        walletAccountId: "wallet-001",
        direction: TransactionDirection.Debit,
        transactionType: TransactionType.Commission,
        amountMinor: 35000,
        currency: "NGN",
        status: TransactionStatus.Completed,
        reference: "COM-REF-004",
        shipmentId: "ship-004",
        metadata: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
        updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      },
      {
        __typename: "Transaction",
        id: "txn-005",
        walletAccountId: "wallet-001",
        direction: TransactionDirection.Credit,
        transactionType: TransactionType.ProviderPayout,
        amountMinor: 180000,
        currency: "NGN",
        status: TransactionStatus.Pending,
        reference: "PAY-REF-005",
        shipmentId: "ship-005",
        metadata: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      },
    ],
  },
};

export const DEV_FREIGHT_DATA: GetProviderMarketplaceTabQuaryQuery = {
  marketplaceShipments: {
    __typename: "MarketplaceShipmentsResult",
    nextCursor: null,
    items: [
      {
        __typename: "Shipment",
        id: "mkt-ship-001",
        trackingCode: "OY-2024-0101",
        status: ShipmentStatus.Broadcasting,
        scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
        createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
        packageDescription: "Fragile glassware – handle with care",
        pricingCurrency: "NGN",
        quotedPriceMinor: 520000,
        finalPriceMinor: null,
        pickupAddressSummary: "14 Marina St, Lagos Island",
        dropoffAddressSummary: "22 Admiralty Way, Lekki Phase 1",
      },
      {
        __typename: "Shipment",
        id: "mkt-ship-002",
        trackingCode: "OY-2024-0102",
        status: ShipmentStatus.Broadcasting,
        scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
        createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        packageDescription: "Groceries and perishables",
        pricingCurrency: "NGN",
        quotedPriceMinor: 185000,
        finalPriceMinor: null,
        pickupAddressSummary: "5 Allen Ave, Ikeja",
        dropoffAddressSummary: "Plot 3 Adeola Odeku, Victoria Island",
      },
      {
        __typename: "Shipment",
        id: "mkt-ship-003",
        trackingCode: "OY-2024-0103",
        status: ShipmentStatus.Broadcasting,
        scheduledAt: null,
        createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        packageDescription: "Documents and paperwork",
        pricingCurrency: "NGN",
        quotedPriceMinor: 95000,
        finalPriceMinor: null,
        pickupAddressSummary: "Block A, Tejuosho Market, Surulere",
        dropoffAddressSummary: "12 Broad St, Lagos Island",
      },
      {
        __typename: "Shipment",
        id: "mkt-ship-004",
        trackingCode: "OY-2024-0104",
        status: ShipmentStatus.Broadcasting,
        scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        packageDescription: "Furniture pieces – two-person lift required",
        pricingCurrency: "NGN",
        quotedPriceMinor: 780000,
        finalPriceMinor: null,
        pickupAddressSummary: "Ojota Bus Stop, Lagos",
        dropoffAddressSummary: "7 Wole Ariyo St, Lekki Phase 2",
      },
    ],
  },
};
